src/objects/CountryCode__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <description>Country Code</description>
        <label>Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>CountryCode</label>
    <nameField>
        <label>CountryCode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountryCodes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/StandardAccountEx.cls
public class StandardAccountEx {

    public boolean billingInfo {get;set;}
    public string abil {get; set;}
    
    public List<CountryCode__c> ccList {get; set;}
    Account a;
         
    public StandardAccountEx(ApexPages.StandardController controller) {
     a = (Account)controller.getRecord();
     billingInfo = false;
    }
 
  public pagereference cSIC(){
   string aSrch = a.billingcountry;
   string aquery = 'Select name, Code__c from CountryCode__c where name = :aSrch';
   
   ccList = database.query(aquery);
   
     for (CountryCode__c cCC : ccList){
         a.sic = cCC.Code__c;
     }
   return null;
 
  }    
          
}